# Generated by Django 2.2.6 on 2019-11-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champ_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_champ_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('name_english', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('line', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('role_img', models.URLField()),
                ('region', models.CharField(max_length=20)),
                ('region_img', models.URLField()),
                ('story', models.TextField(max_length=200)),
                ('passive_name', models.CharField(max_length=20)),
                ('passive_desc', models.TextField(max_length=200)),
                ('passive_icon', models.URLField()),
                ('q_skill_name', models.CharField(max_length=20)),
                ('q_skill_desc', models.TextField(max_length=200)),
                ('q_skill_icon', models.URLField()),
                ('w_skill_name', models.CharField(max_length=20)),
                ('w_skill_desc', models.TextField(max_length=200)),
                ('w_skill_icon', models.URLField()),
                ('e_skill_name', models.CharField(max_length=20)),
                ('e_skill_desc', models.TextField(max_length=200)),
                ('e_skill_icon', models.URLField()),
                ('r_skill_name', models.CharField(max_length=20)),
                ('r_skill_desc', models.TextField(max_length=200)),
                ('r_skill_icon', models.URLField()),
                ('small_icon', models.URLField()),
                ('loading_img', models.URLField()),
                ('splash_video', models.URLField()),
                ('splash_origin', models.URLField()),
                ('splash_skin1', models.URLField(null=True)),
                ('splash_skin2', models.URLField(null=True)),
                ('splash_skin3', models.URLField(null=True)),
                ('splash_skin4', models.URLField(null=True)),
                ('splash_skin5', models.URLField(null=True)),
                ('splash_skin6', models.URLField(null=True)),
                ('splash_skin7', models.URLField(null=True)),
                ('splash_skin8', models.URLField(null=True)),
                ('splash_skin9', models.URLField(null=True)),
            ],
            options={
                'db_table': 'champ_infos',
            },
        ),
    ]
