# Generated by Django 2.2.6 on 2019-11-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champion_infos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champ_info',
            name='e_skill_desc',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='champ_info',
            name='passive_desc',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='champ_info',
            name='q_skill_desc',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='champ_info',
            name='r_skill_desc',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='champ_info',
            name='w_skill_desc',
            field=models.TextField(max_length=300),
        ),
    ]
