# Generated by Django 2.2.6 on 2019-11-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champion_infos', '0003_auto_20191107_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champ_info',
            name='story',
            field=models.TextField(max_length=700),
        ),
    ]
