# Generated by Django 2.2.6 on 2019-11-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spell_name', models.CharField(max_length=20, unique=True)),
                ('spell_img_src', models.CharField(max_length=500)),
                ('riot_spell_id', models.IntegerField()),
            ],
            options={
                'db_table': 'spells',
            },
        ),
    ]
