# Generated by Django 2.2.6 on 2019-11-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='spell_desc',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
