# Generated by Django 2.2.6 on 2019-11-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0002_spell_spell_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='spell_img_src',
            field=models.URLField(max_length=3000),
        ),
    ]
