# Generated by Django 2.2.6 on 2019-11-07 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('champions', '0001_initial'),
        ('spells', '0003_auto_20191105_1343'),
        ('core_rune', '0002_auto_20191105_1344'),
        ('subrune_category', '0003_auto_20191105_1344'),
        ('account', '0003_auto_20191103_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.CharField(max_length=10)),
                ('kill', models.IntegerField()),
                ('death', models.IntegerField()),
                ('assist', models.IntegerField()),
                ('champion_level', models.IntegerField()),
                ('cs_neutrals', models.IntegerField()),
                ('cs_minions', models.IntegerField()),
                ('start_time', models.DateField()),
                ('lane', models.CharField(max_length=10)),
                ('blue_first_user_name', models.CharField(max_length=20)),
                ('blue_user_second_name', models.CharField(max_length=20)),
                ('blue_user_third_name', models.CharField(max_length=20)),
                ('blue_user_fourth_name', models.CharField(max_length=20)),
                ('blue_user_fifth_name', models.CharField(max_length=20)),
                ('red_user_first_name', models.CharField(max_length=20)),
                ('red_user_second_name', models.CharField(max_length=20)),
                ('red_user_third_name', models.CharField(max_length=20)),
                ('red_user_fourth_name', models.CharField(max_length=20)),
                ('red_user_fifth_name', models.CharField(max_length=20)),
                ('gameduration', models.TimeField()),
                ('doublekill', models.IntegerField()),
                ('triplekill', models.IntegerField()),
                ('quadrakill', models.IntegerField()),
                ('pentakill', models.IntegerField()),
                ('gamemode', models.CharField(max_length=20)),
                ('blue_first_user_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_first_user_champions', to='champions.Champions')),
                ('blue_user_fifth_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_user_fifth_champions', to='champions.Champions')),
                ('blue_user_fourth_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_user_fourth_champions', to='champions.Champions')),
                ('blue_user_second_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_user_second_champions', to='champions.Champions')),
                ('blue_user_third_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_user_third_champions', to='champions.Champions')),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.Champions')),
                ('core_rune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_runes', to='core_rune.Core_rune')),
                ('red_user_fifth_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_user_fifth_champions', to='champions.Champions')),
                ('red_user_first_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_user_first_champions', to='champions.Champions')),
                ('red_user_fourth_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_user_fourth_champions', to='champions.Champions')),
                ('red_user_second_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_user_second_champions', to='champions.Champions')),
                ('red_user_thrid_champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_user_thrid_champions', to='champions.Champions')),
                ('spell1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell1', to='spells.Spell')),
                ('spell2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spell2', to='spells.Spell')),
                ('sub_rune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_runes', to='subrune_category.Subrune_category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
    ]
