# Generated by Django 2.2.6 on 2019-11-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subrune_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subrune_category_name', models.CharField(max_length=20)),
                ('subrune_category_img', models.CharField(max_length=500)),
                ('riot_subrune_category_id', models.IntegerField()),
                ('subrune_category_desc', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'subrune_categories',
            },
        ),
    ]
