# Generated by Django 2.2.6 on 2019-11-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subrune_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrune_category',
            name='subrune_category_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
