# Generated by Django 2.2.6 on 2019-11-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subrune_category', '0002_auto_20191104_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrune_category',
            name='subrune_category_img',
            field=models.URLField(max_length=3000),
        ),
    ]
