# Generated by Django 2.2.6 on 2019-11-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tierstat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(max_length=20)),
                ('tier_numbers', models.CharField(max_length=5)),
                ('summoner', models.IntegerField()),
                ('summoner_percent', models.FloatField()),
                ('aggregate', models.IntegerField()),
                ('aggregate_percent', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tierstats',
            },
        ),
    ]
