# Generated by Django 2.2.6 on 2019-11-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core_rune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rune_name', models.CharField(max_length=20, unique=True)),
                ('rune_img_src', models.CharField(max_length=500)),
                ('riot_rune_id', models.IntegerField()),
                ('rune_description', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'core_runes',
            },
        ),
    ]
