# Generated by Django 2.2.6 on 2019-11-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_rune', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core_rune',
            name='rune_img_src',
            field=models.URLField(max_length=3000),
        ),
    ]
