# Generated by Django 2.2.6 on 2019-11-01 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('champions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat_champions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_rates', models.DecimalField(decimal_places=2, max_digits=4)),
                ('player_numbers', models.IntegerField()),
                ('kda', models.CharField(max_length=10)),
                ('cs_avg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gold_avg', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('champions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champions.Champions')),
            ],
            options={
                'db_table': 'stat_champions',
            },
        ),
    ]
