# Generated by Django 2.2.6 on 2019-10-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_name', models.CharField(max_length=15, unique=True)),
                ('champion_img_src', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'champions',
            },
        ),
    ]
